event_homepage:
    path:     /hello/{firstName}/{count}
    defaults: { _controller: EventBundle:Default:index }

event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"

event_annotation:
    resource: "@EventBundle/Controller"
    type:     annotation
